-- Run this once in Supabase: Dashboard > SQL Editor > New query > paste this > Run

create table if not exists runs (
  id bigint generated by default as identity primary key,
  status text not null,
  details jsonb,
  created_at timestamptz not null default now()
);
